services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  phppgadmin:
    restart: unless-stopped
    image: zhajor/docker-phppgadmin:latest
    ports:
      - "8988:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  fastapi:
    restart: unless-stopped
    build: .
    ports:
      - "8989:8989"
    depends_on:
      - postgres

volumes:
  pgdata:

