services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8988:8080

  fastapi:
    restart: unless-stopped
    container_name: fastapi
    build: .
    ports:
      - 8989:8989
    depends_on:
      - postgres

volumes:
  pgdata:

