#!/bin/bash

file=~/.hgyuser

if [ ! -f "$file" ]; then
	echo "first time using the script plz input your usercode(4 number):"
	read user
	#user=$((16#${usercode}))
	echo "${user}" > ~/.hgyuser
fi

usercodeo=$(cat ~/.hgyuser)
echo "input your usercode:"
read usercode
#usercodej=$((16#${usercodei}))

if [ $usercode -eq $usercodeo ]; then

	let userl=${#usercode}
	let sum=0
	for ((b=0;b<userl;b++));do
		uid[b]=${usercode:b:1}
		#字符串分割
		let sum=${sum}+${uid[b]}
	done
	#echo "$sum"
	let sum=${sum}/${userl}
	#echo "$sum"
	
	echo "decrypt from file or input? 1:file(from ~/) 2:input"
	read mode
	if [ ${mode} -eq 1 ]; then
		echo "nameforsavedfile?"
		read savename
		if [ ! -f "~/hgycrypted-${savename}" ]; then
			password=$(cat ~/hgycrypted-${savename})
		else
			echo "encrypted file not exists!"
			exit
		fi
	else
		echo "input your crypt-password:"
		read password
	fi
		
	let l=${#password}

	for ((a=0;a<l;a++));do
		var[a]=${password:a:1}
		pass[a]=$(printf "%d" "'${var[a]}")
		let pass[a]=pass[a]-sum
		#echo "分割：${pass[a]}"
	done

	for ((a=0;a<l;a++));do
		key[a]=$(printf \\x`printf %x ${pass[a]}`)
		#echo "${key[a]}"
	done

	for ((a=l-1;a>=0;a--));do
		out=${out}${key[a]}
	done

	echo "decrypted：${out}"

else
	echo "wrong usercode"
fi
